#ifndef __ABC_COMPONENT_CONSTDEF_H__
#define __ABC_COMPONENT_CONSTDEF_H__


enum ABC_FUNCTION {
	FUNCTION_ABC_OPEN,
	FUNCTION_ABC_SEND,
	FUNCTION_ABC_SENT,
	FUNCTION_ABC_CLOSE,
	FUNCTION_ABC_INPUT,
	FUNCTION_ABC_LAST,
};

#define ABC_NUM_REQUIRED_OBJECTS 0
#define ABC_NUM_REQUIRED_HILOBJECTS 0

#endif /*__ABC_COMPONENT_CONSTDEF_H__*/
