#ifndef __CHAMELEON_COMPONENT_CONSTDEF_H__
#define __CHAMELEON_COMPONENT_CONSTDEF_H__


enum CHAMELEON_FUNCTION {
	FUNCTION_CHAMELEON_CREATE,
	FUNCTION_CHAMELEON_PARSE,
	FUNCTION_CHAMELEON_INIT,
	FUNCTION_CHAMELEON_HDRSIZE,
	FUNCTION_CHAMELEON_LAST,
};

#define CHAMELEON_NUM_REQUIRED_OBJECTS 0
#define CHAMELEON_NUM_REQUIRED_HILOBJECTS 0

#endif /*__CHAMELEON_COMPONENT_CONSTDEF_H__*/
