#ifndef __CHANNEL_COMPONENT_CONSTDEF_H__
#define __CHANNEL_COMPONENT_CONSTDEF_H__


enum CHANNEL_FUNCTION {
	FUNCTION_CHANNEL_INIT,
	FUNCTION_CHANNEL_OPEN,
	FUNCTION_CHANNEL_SET_ATTRIBUTES,
	FUNCTION_CHANNEL_CLOSE,
	FUNCTION_CHANNEL_LOOKUP,
	FUNCTION_CHANNEL_LAST,
};

#define CHANNEL_NUM_REQUIRED_OBJECTS 0
#define CHANNEL_NUM_REQUIRED_HILOBJECTS 0

#endif /*__CHANNEL_COMPONENT_CONSTDEF_H__*/
