#ifndef __NBR_TABLE_COMPONENT_CONSTDEF_H__
#define __NBR_TABLE_COMPONENT_CONSTDEF_H__


enum NBR_TABLE_FUNCTION {
	FUNCTION_NBR_TABLE_ADD_LLADDR,
	FUNCTION_NBR_TABLE_HEAD,
	FUNCTION_NBR_TABLE_REGISTER,
	FUNCTION_NBR_TABLE_LOCK,
	FUNCTION_NBR_TABLE_NEXT,
	FUNCTION_NBR_TABLE_GET_LLADDR,
	FUNCTION_NBR_TABLE_REMOVE,
	FUNCTION_NBR_TABLE_GET_FROM_LLADDR,
	FUNCTION_NBR_TABLE_UNLOCK,
	FUNCTION_NBR_TABLE_LAST,
};

#define NBR_TABLE_NUM_REQUIRED_OBJECTS 0
#define NBR_TABLE_NUM_REQUIRED_HILOBJECTS 0

#endif /*__NBR_TABLE_COMPONENT_CONSTDEF_H__*/
