#ifndef __PACKETQUEUE_COMPONENT_CONSTDEF_H__
#define __PACKETQUEUE_COMPONENT_CONSTDEF_H__


enum PACKETQUEUE_FUNCTION {
	FUNCTION_PACKETQUEUE_LEN,
	FUNCTION_PACKETQUEUE_FIRST,
	FUNCTION_PACKETQUEUE_ENQUEUE_PACKETBUF,
	FUNCTION_PACKETQUEUE_INIT,
	FUNCTION_PACKETQUEUE_PTR,
	FUNCTION_PACKETQUEUE_DEQUEUE,
	FUNCTION_PACKETQUEUE_QUEUEBUF,
	FUNCTION_PACKETQUEUE_LAST,
};

#define PACKETQUEUE_NUM_REQUIRED_OBJECTS 0
#define PACKETQUEUE_NUM_REQUIRED_HILOBJECTS 0

#endif /*__PACKETQUEUE_COMPONENT_CONSTDEF_H__*/
