#ifndef __QUEUEBUF_COMPONENT_CONSTDEF_H__
#define __QUEUEBUF_COMPONENT_CONSTDEF_H__


enum QUEUEBUF_FUNCTION {
	FUNCTION_QUEUEBUF_DATAPTR,
	FUNCTION_QUEUEBUF_ADDR,
	FUNCTION_QUEUEBUF_NEW_FROM_PACKETBUF,
	FUNCTION_QUEUEBUF_FREE,
	FUNCTION_QUEUEBUF_TO_PACKETBUF,
	FUNCTION_QUEUEBUF_ATTR,
	FUNCTION_QUEUEBUF_DATALEN,
	FUNCTION_QUEUEBUF_INIT,
	FUNCTION_QUEUEBUF_DEBUG_PRINT,
	FUNCTION_QUEUEBUF_UPDATE_ATTR_FROM_PACKETBUF,
	FUNCTION_QUEUEBUF_LAST,
};

#define QUEUEBUF_NUM_REQUIRED_OBJECTS 0
#define QUEUEBUF_NUM_REQUIRED_HILOBJECTS 0

#endif /*__QUEUEBUF_COMPONENT_CONSTDEF_H__*/
