#ifndef __RIMEADDR_COMPONENT_CONSTDEF_H__
#define __RIMEADDR_COMPONENT_CONSTDEF_H__


enum RIMEADDR_FUNCTION {
	FUNCTION_RIMEADDR_GET_NULL,
	FUNCTION_RIMEADDR_CMP,
	FUNCTION_RIMEADDR_SET_NODE_ADDR,
	FUNCTION_RIMEADDR_GET_NODE_ADDR,
	FUNCTION_RIMEADDR_COPY,
	FUNCTION_RIMEADDR_LAST,
};

#define RIMEADDR_NUM_REQUIRED_OBJECTS 0
#define RIMEADDR_NUM_REQUIRED_HILOBJECTS 0

#endif /*__RIMEADDR_COMPONENT_CONSTDEF_H__*/
