#ifndef __PHASE_HIL_COMPONENT_CONSTDEF_H__
#define __PHASE_HIL_COMPONENT_CONSTDEF_H__

enum PHASE_FUNCTION {
	FUNCTION_PHASE_INIT,
	FUNCTION_PHASE_WAIT,
	FUNCTION_PHASE_UPDATE,
	FUNCTION_PHASE_LAST,
};

#endif /*__PHASE_HIL_COMPONENT_CONSTDEF_H__*/
