#ifndef __PHASE_COMPONENT_CONSTDEF_H__
#define __PHASE_COMPONENT_CONSTDEF_H__


enum PHASE_FUNCTION {
	FUNCTION_PHASE_INIT,
	FUNCTION_PHASE_UPDATE,
	FUNCTION_PHASE_WAIT,
	FUNCTION_PHASE_LAST,
};

#define PHASE_NUM_REQUIRED_OBJECTS 0
#define PHASE_NUM_REQUIRED_HILOBJECTS 0

#endif /*__PHASE_COMPONENT_CONSTDEF_H__*/
