#ifndef __XMAC_COMPONENT_CONSTDEF_H__
#define __XMAC_COMPONENT_CONSTDEF_H__


enum XMAC_FUNCTION {
	FUNCTION_XMAC_SET_ANNOUNCEMENT_RADIO_TXPOWER,
	FUNCTION_XMAC_LAST,
};

#define XMAC_NUM_REQUIRED_OBJECTS 0
#define XMAC_NUM_REQUIRED_HILOBJECTS 0

#endif /*__XMAC_COMPONENT_CONSTDEF_H__*/
