#ifndef __CSMA_HIL_COMPONENT_CONSTDEF_H__
#define __CSMA_HIL_COMPONENT_CONSTDEF_H__


enum CSMA_FUNCTION {
	FUNCTION_CSMA_LAST,
};


enum CSMA_PROCESSES {
	PROCESS_CSMA_LAST,
};


#endif /*__CSMA_HIL_COMPONENT_CONSTDEF_H__*/
