#ifndef __XMAC_HIL_COMPONENT_CONSTDEF_H__
#define __XMAC_HIL_COMPONENT_CONSTDEF_H__


enum XMAC_FUNCTION {
	FUNCTION_XMAC_SET_ANNOUNCEMENT_RADIO_TXPOWER,
	FUNCTION_XMAC_LAST,
};


enum XMAC_PROCESSES {
	PROCESS_XMAC_LAST,
};


#endif /*__XMAC_HIL_COMPONENT_CONSTDEF_H__*/
