#ifndef __ABC_HIL_COMPONENT_CONSTDEF_H__
#define __ABC_HIL_COMPONENT_CONSTDEF_H__


enum ABC_FUNCTION {
	FUNCTION_ABC_CLOSE,
	FUNCTION_ABC_INPUT,
	FUNCTION_ABC_OPEN,
	FUNCTION_ABC_SEND,
	FUNCTION_ABC_SENT,
	FUNCTION_ABC_LAST,
};


enum ABC_PROCESSES {
	PROCESS_ABC_LAST,
};


#endif /*__ABC_HIL_COMPONENT_CONSTDEF_H__*/
