#ifndef __ANNOUNCEMENT_HIL_COMPONENT_CONSTDEF_H__
#define __ANNOUNCEMENT_HIL_COMPONENT_CONSTDEF_H__


enum ANNOUNCEMENT_FUNCTION {
	FUNCTION_ANNOUNCEMENT_BUMP,
	FUNCTION_ANNOUNCEMENT_SET_VALUE,
	FUNCTION_ANNOUNCEMENT_REGISTER_OBSERVER_CALLBACK,
	FUNCTION_ANNOUNCEMENT_INIT,
	FUNCTION_ANNOUNCEMENT_LIST,
	FUNCTION_ANNOUNCEMENT_LISTEN,
	FUNCTION_ANNOUNCEMENT_REMOVE,
	FUNCTION_ANNOUNCEMENT_HEARD,
	FUNCTION_ANNOUNCEMENT_REGISTER_LISTEN_CALLBACK,
	FUNCTION_ANNOUNCEMENT_REMOVE_VALUE,
	FUNCTION_ANNOUNCEMENT_REGISTER,
	FUNCTION_ANNOUNCEMENT_LAST,
};


enum ANNOUNCEMENT_PROCESSES {
	PROCESS_ANNOUNCEMENT_LAST,
};


#endif /*__ANNOUNCEMENT_HIL_COMPONENT_CONSTDEF_H__*/
