#ifndef __CHANNEL_HIL_COMPONENT_CONSTDEF_H__
#define __CHANNEL_HIL_COMPONENT_CONSTDEF_H__

enum CHANNEL_FUNCTION {
	FUNCTION_CHANNEL_LOOKUP,
	FUNCTION_CHANNEL_OPEN,
	FUNCTION_CHANNEL_SET_ATTRIBUTES,
	FUNCTION_CHANNEL_CLOSE,
	FUNCTION_CHANNEL_INIT,
	FUNCTION_CHANNEL_LAST,
};

#endif /*__CHANNEL_HIL_COMPONENT_CONSTDEF_H__*/
