#ifndef __PACKETQUEUE_HIL_COMPONENT_CONSTDEF_H__
#define __PACKETQUEUE_HIL_COMPONENT_CONSTDEF_H__


enum PACKETQUEUE_FUNCTION {
	FUNCTION_PACKETQUEUE_ENQUEUE_PACKETBUF,
	FUNCTION_PACKETQUEUE_FIRST,
	FUNCTION_PACKETQUEUE_DEQUEUE,
	FUNCTION_PACKETQUEUE_PTR,
	FUNCTION_PACKETQUEUE_QUEUEBUF,
	FUNCTION_PACKETQUEUE_INIT,
	FUNCTION_PACKETQUEUE_LEN,
	FUNCTION_PACKETQUEUE_LAST,
};


enum PACKETQUEUE_PROCESSES {
	PROCESS_PACKETQUEUE_LAST,
};


#endif /*__PACKETQUEUE_HIL_COMPONENT_CONSTDEF_H__*/
