#ifndef __RIMEADDR_HIL_COMPONENT_CONSTDEF_H__
#define __RIMEADDR_HIL_COMPONENT_CONSTDEF_H__

enum RIMEADDR_FUNCTION {
	FUNCTION_RIMEADDR_SET_NODE_ADDR,
	FUNCTION_RIMEADDR_CMP,
	FUNCTION_RIMEADDR_COPY,
	FUNCTION_RIMEADDR_LAST,
};

#endif /*__RIMEADDR_HIL_COMPONENT_CONSTDEF_H__*/
