#ifndef __COMPOWER_COMPONENT_CONSTDEF_H__
#define __COMPOWER_COMPONENT_CONSTDEF_H__


enum COMPOWER_FUNCTION {
	FUNCTION_COMPOWER_ATTRCONV,
	FUNCTION_COMPOWER_INIT,
	FUNCTION_COMPOWER_CLEAR,
	FUNCTION_COMPOWER_ACCUMULATE_ATTRS,
	FUNCTION_COMPOWER_ACCUMULATE,
	FUNCTION_COMPOWER_LAST,
};

#define COMPOWER_NUM_REQUIRED_OBJECTS 0
#define COMPOWER_NUM_REQUIRED_HILOBJECTS 0

#endif /*__COMPOWER_COMPONENT_CONSTDEF_H__*/
