#ifndef __CRC16_COMPONENT_CONSTDEF_H__
#define __CRC16_COMPONENT_CONSTDEF_H__


enum CRC16_FUNCTION {
	FUNCTION_CRC16_ADD,
	FUNCTION_CRC16_DATA,
	FUNCTION_CRC16_LAST,
};

#define CRC16_NUM_REQUIRED_OBJECTS 0
#define CRC16_NUM_REQUIRED_HILOBJECTS 0

#endif /*__CRC16_COMPONENT_CONSTDEF_H__*/
