#ifndef __ENERGEST_COMPONENT_CONSTDEF_H__
#define __ENERGEST_COMPONENT_CONSTDEF_H__


enum ENERGEST_FUNCTION {
	FUNCTION_ENERGEST_INIT,
	FUNCTION_ENERGEST_FLUSH,
	FUNCTION_ENERGEST_TYPE_SET,
	FUNCTION_ENERGEST_TYPE_TIME,
	FUNCTION_ENERGEST_LAST,
};

#define ENERGEST_NUM_REQUIRED_OBJECTS 0
#define ENERGEST_NUM_REQUIRED_HILOBJECTS 0

#endif /*__ENERGEST_COMPONENT_CONSTDEF_H__*/
