#ifndef __MEMB_HIL_COMPONENT_CONSTDEF_H__
#define __MEMB_HIL_COMPONENT_CONSTDEF_H__

enum MEMB_FUNCTION {
	FUNCTION_MEMB_FREE,
	FUNCTION_MEMB_ALLOC,
	FUNCTION_MEMB_INMEMB,
	FUNCTION_MEMB_INIT,
	FUNCTION_MEMB_LAST,
};

#endif /*__MEMB_HIL_COMPONENT_CONSTDEF_H__*/
