#ifndef __MEMB_COMPONENT_CONSTDEF_H__
#define __MEMB_COMPONENT_CONSTDEF_H__


enum MEMB_FUNCTION {
	FUNCTION_MEMB_ALLOC,
	FUNCTION_MEMB_FREE,
	FUNCTION_MEMB_INIT,
	FUNCTION_MEMB_INMEMB,
	FUNCTION_MEMB_LAST,
};

#define MEMB_NUM_REQUIRED_OBJECTS 0
#define MEMB_NUM_REQUIRED_HILOBJECTS 0

#endif /*__MEMB_COMPONENT_CONSTDEF_H__*/
