#ifndef __NODE_ID_COMPONENT_CONSTDEF_H__
#define __NODE_ID_COMPONENT_CONSTDEF_H__


enum NODE_ID_FUNCTION {
	FUNCTION_NODE_ID_RESTORE,
	FUNCTION_NODE_ID_BURN,
	FUNCTION_NODE_ID_LAST,
};

#define NODE_ID_NUM_REQUIRED_OBJECTS 0
#define NODE_ID_NUM_REQUIRED_HILOBJECTS 0

#endif /*__NODE_ID_COMPONENT_CONSTDEF_H__*/
