#ifndef __RANDOM_COMPONENT_CONSTDEF_H__
#define __RANDOM_COMPONENT_CONSTDEF_H__


enum RANDOM_FUNCTION {
	FUNCTION_RANDOM_RAND,
	FUNCTION_RANDOM_INIT,
	FUNCTION_RANDOM_LAST,
};

#define RANDOM_NUM_REQUIRED_OBJECTS 0
#define RANDOM_NUM_REQUIRED_HILOBJECTS 0

#endif /*__RANDOM_COMPONENT_CONSTDEF_H__*/
