#ifndef __RINGBUF_COMPONENT_CONSTDEF_H__
#define __RINGBUF_COMPONENT_CONSTDEF_H__


enum RINGBUF_FUNCTION {
	FUNCTION_RINGBUF_INIT,
	FUNCTION_RINGBUF_SIZE,
	FUNCTION_RINGBUF_PUT,
	FUNCTION_RINGBUF_GET,
	FUNCTION_RINGBUF_ELEMENTS,
	FUNCTION_RINGBUF_LAST,
};

#define RINGBUF_NUM_REQUIRED_OBJECTS 0
#define RINGBUF_NUM_REQUIRED_HILOBJECTS 0

#endif /*__RINGBUF_COMPONENT_CONSTDEF_H__*/
