#ifndef __NETSTACK_COMPONENT_CONSTDEF_H__
#define __NETSTACK_COMPONENT_CONSTDEF_H__


enum NETSTACK_FUNCTION {
	FUNCTION_NETSTACK_INIT,
	FUNCTION_NETSTACK_LAST,
};

#define NETSTACK_NUM_REQUIRED_OBJECTS 0
#define NETSTACK_NUM_REQUIRED_HILOBJECTS 0

#endif /*__NETSTACK_COMPONENT_CONSTDEF_H__*/
