#ifndef __RIME_COMPONENT_CONSTDEF_H__
#define __RIME_COMPONENT_CONSTDEF_H__


enum RIME_FUNCTION {
	FUNCTION_RIME_SNIFFER_REMOVE,
	FUNCTION_RIME_OUTPUT,
	FUNCTION_RIME_SNIFFER_ADD,
	FUNCTION_RIME_LAST,
};

#define RIME_NUM_REQUIRED_OBJECTS 0
#define RIME_NUM_REQUIRED_HILOBJECTS 0

#endif /*__RIME_COMPONENT_CONSTDEF_H__*/
