#ifndef __CLOCK_COMPONENT_CONSTDEF_H__
#define __CLOCK_COMPONENT_CONSTDEF_H__


enum CLOCK_FUNCTION {
	FUNCTION_CLOCK_TIME,
	FUNCTION_CLOCK_INIT,
	FUNCTION_CLOCK_DELAY,
	FUNCTION_CLOCK_FINE,
	FUNCTION_CLOCK_SECONDS,
	FUNCTION_CLOCK_FINE_MAX,
	FUNCTION_CLOCK_WAIT,
	FUNCTION_CLOCK_SET_SECONDS,
	FUNCTION_CLOCK_LAST,
};

#define CLOCK_NUM_REQUIRED_OBJECTS 0
#define CLOCK_NUM_REQUIRED_HILOBJECTS 0

#endif /*__CLOCK_COMPONENT_CONSTDEF_H__*/
