#ifndef __CTIMER_COMPONENT_CONSTDEF_H__
#define __CTIMER_COMPONENT_CONSTDEF_H__


enum CTIMER_FUNCTION {
	FUNCTION_CTIMER_INIT,
	FUNCTION_CTIMER_RESTART,
	FUNCTION_CTIMER_EXPIRED,
	FUNCTION_CTIMER_SET,
	FUNCTION_CTIMER_RESET,
	FUNCTION_CTIMER_STOP,
	FUNCTION_CTIMER_LAST,
};

#define CTIMER_NUM_REQUIRED_OBJECTS 0
#define CTIMER_NUM_REQUIRED_HILOBJECTS 0

#endif /*__CTIMER_COMPONENT_CONSTDEF_H__*/
