#ifndef __RTIMER_COMPONENT_CONSTDEF_H__
#define __RTIMER_COMPONENT_CONSTDEF_H__


enum RTIMER_FUNCTION {
	FUNCTION_RTIMER_INIT,
	FUNCTION_RTIMER_RUN_NEXT,
	FUNCTION_RTIMER_SET,
	FUNCTION_RTIMER_NOW,
	FUNCTION_RTIMER_LAST,
};

#define RTIMER_NUM_REQUIRED_OBJECTS 0
#define RTIMER_NUM_REQUIRED_HILOBJECTS 0

#endif /*__RTIMER_COMPONENT_CONSTDEF_H__*/
