#ifndef __STIMER_COMPONENT_CONSTDEF_H__
#define __STIMER_COMPONENT_CONSTDEF_H__


enum STIMER_FUNCTION {
	FUNCTION_STIMER_RESTART,
	FUNCTION_STIMER_RESET,
	FUNCTION_STIMER_REMAINING,
	FUNCTION_STIMER_ELAPSED,
	FUNCTION_STIMER_EXPIRED,
	FUNCTION_STIMER_SET,
	FUNCTION_STIMER_LAST,
};

#define STIMER_NUM_REQUIRED_OBJECTS 0
#define STIMER_NUM_REQUIRED_HILOBJECTS 0

#endif /*__STIMER_COMPONENT_CONSTDEF_H__*/
