#ifndef __TIMER_COMPONENT_CONSTDEF_H__
#define __TIMER_COMPONENT_CONSTDEF_H__


enum TIMER_FUNCTION {
	FUNCTION_TIMER_RESET,
	FUNCTION_TIMER_REMAINING,
	FUNCTION_TIMER_SET,
	FUNCTION_TIMER_EXPIRED,
	FUNCTION_TIMER_RESTART,
	FUNCTION_TIMER_LAST,
};

#define TIMER_NUM_REQUIRED_OBJECTS 0
#define TIMER_NUM_REQUIRED_HILOBJECTS 0

#endif /*__TIMER_COMPONENT_CONSTDEF_H__*/
