#ifndef __COMPOWER_HIL_COMPONENT_CONSTDEF_H__
#define __COMPOWER_HIL_COMPONENT_CONSTDEF_H__


enum COMPOWER_FUNCTION {
	FUNCTION_COMPOWER_ACCUMULATE,
	FUNCTION_COMPOWER_CLEAR,
	FUNCTION_COMPOWER_ACCUMULATE_ATTRS,
	FUNCTION_COMPOWER_INIT,
	FUNCTION_COMPOWER_ATTRCONV,
	FUNCTION_COMPOWER_LAST,
};


enum COMPOWER_PROCESSES {
	PROCESS_COMPOWER_LAST,
};


#endif /*__COMPOWER_HIL_COMPONENT_CONSTDEF_H__*/
