#ifndef __CRC16_HIL_COMPONENT_CONSTDEF_H__
#define __CRC16_HIL_COMPONENT_CONSTDEF_H__


enum CRC16_FUNCTION {
	FUNCTION_CRC16_ADD,
	FUNCTION_CRC16_DATA,
	FUNCTION_CRC16_LAST,
};


enum CRC16_PROCESSES {
	PROCESS_CRC16_LAST,
};


#endif /*__CRC16_HIL_COMPONENT_CONSTDEF_H__*/
