#ifndef __ENERGEST_HIL_COMPONENT_CONSTDEF_H__
#define __ENERGEST_HIL_COMPONENT_CONSTDEF_H__


enum ENERGEST_FUNCTION {
	FUNCTION_ENERGEST_TYPE_SET,
	FUNCTION_ENERGEST_INIT,
	FUNCTION_ENERGEST_FLUSH,
	FUNCTION_ENERGEST_TYPE_TIME,
	FUNCTION_ENERGEST_LAST,
};


enum ENERGEST_PROCESSES {
	PROCESS_ENERGEST_LAST,
};


#endif /*__ENERGEST_HIL_COMPONENT_CONSTDEF_H__*/
