#ifndef __LIST_HIL_COMPONENT_CONSTDEF_H__
#define __LIST_HIL_COMPONENT_CONSTDEF_H__

enum LIST_FUNCTION {
	FUNCTION_LIST_TAIL,
	FUNCTION_LIST_ADD,
	FUNCTION_LIST_ITEM_NEXT,
	FUNCTION_LIST_HEAD,
	FUNCTION_LIST_CHOP,
	FUNCTION_LIST_INIT,
	FUNCTION_LIST_INSERT,
	FUNCTION_LIST_REMOVE,
	FUNCTION_LIST_COPY,
	FUNCTION_LIST_PUSH,
	FUNCTION_LIST_POP,
	FUNCTION_LIST_LENGTH,
	FUNCTION_LIST_LAST,
};

#endif /*__LIST_HIL_COMPONENT_CONSTDEF_H__*/
