#ifndef __NODE_ID_HIL_COMPONENT_CONSTDEF_H__
#define __NODE_ID_HIL_COMPONENT_CONSTDEF_H__


enum NODE_ID_FUNCTION {
	FUNCTION_NODE_ID_BURN,
	FUNCTION_NODE_ID_RESTORE,
	FUNCTION_NODE_ID_LAST,
};


enum NODE_ID_PROCESSES {
	PROCESS_NODE_ID_LAST,
};


#endif /*__NODE_ID_HIL_COMPONENT_CONSTDEF_H__*/
