#ifndef __RANDOM_HIL_COMPONENT_CONSTDEF_H__
#define __RANDOM_HIL_COMPONENT_CONSTDEF_H__


enum RANDOM_FUNCTION {
	FUNCTION_RANDOM_INIT,
	FUNCTION_RANDOM_RAND,
	FUNCTION_RANDOM_LAST,
};


enum RANDOM_PROCESSES {
	PROCESS_RANDOM_LAST,
};


#endif /*__RANDOM_HIL_COMPONENT_CONSTDEF_H__*/
