#ifndef __RINGBUF_HIL_COMPONENT_CONSTDEF_H__
#define __RINGBUF_HIL_COMPONENT_CONSTDEF_H__


enum RINGBUF_FUNCTION {
	FUNCTION_RINGBUF_SIZE,
	FUNCTION_RINGBUF_GET,
	FUNCTION_RINGBUF_PUT,
	FUNCTION_RINGBUF_INIT,
	FUNCTION_RINGBUF_ELEMENTS,
	FUNCTION_RINGBUF_LAST,
};


enum RINGBUF_PROCESSES {
	PROCESS_RINGBUF_LAST,
};


#endif /*__RINGBUF_HIL_COMPONENT_CONSTDEF_H__*/
