#ifndef __STRING_HIL_COMPONENT_CONSTDEF_H__
#define __STRING_HIL_COMPONENT_CONSTDEF_H__


enum STRING_FUNCTION {
	FUNCTION_STRING_MEMCCPY,
	FUNCTION_STRING_MEMCHR,
	FUNCTION_STRING_MEMCMP,
	FUNCTION_STRING_MEMCPY,
	FUNCTION_STRING_MEMMOVE,
	FUNCTION_STRING_STRCAT,
	FUNCTION_STRING_STRCHR,
	FUNCTION_STRING_STRCMP,
	FUNCTION_STRING_STRCPY,
	FUNCTION_STRING_STRCASECMP,
	FUNCTION_STRING_STRLEN,
	FUNCTION_STRING_STRLWR,
	FUNCTION_STRING_STRNCAT,
	FUNCTION_STRING_STRNCMP,
	FUNCTION_STRING_STRNCPY ,
	FUNCTION_STRING_STRNCASECMP,
	FUNCTION_STRING_STRNLEN,
	FUNCTION_STRING_STRRCHR,
	FUNCTION_STRING_STRREV,
	FUNCTION_STRING_STRSTR,
	FUNCTION_STRING_STRUPR,
	FUNCTION_STRING_BCMP,
	FUNCTION_STRING_STRSEP,
	FUNCTION_STRING_BCOPY,
	FUNCTION_STRING_STRLCAT,
	FUNCTION_STRING_MEMSET,
	FUNCTION_STRING_BZERO,
	FUNCTION_STRING_STRLCPY,
	FUNCTION_STRING_STRDUP,
	FUNCTION_STRING_SWAB,
	FUNCTION_STRING_STRTOK_R,
	FUNCTION_STRING_STRTOK,
	FUNCTION_STRING_STRSPN,
	FUNCTION_STRING_STRCSPN,
	FUNCTION_STRING_STRPBRK,
	FUNCTION_STRING_LAST,
};


enum STRING_PROCESSES {
	PROCESS_STRING_LAST,
};


#endif /*__STRING_HIL_COMPONENT_CONSTDEF_H__*/

