#ifndef __NETSTACK_HIL_COMPONENT_CONSTDEF_H__
#define __NETSTACK_HIL_COMPONENT_CONSTDEF_H__


enum NETSTACK_FUNCTION {
	FUNCTION_NETSTACK_INIT,
	FUNCTION_NETSTACK_LAST,
};


enum NETSTACK_PROCESSES {
	PROCESS_NETSTACK_LAST,
};


#endif /*__NETSTACK_HIL_COMPONENT_CONSTDEF_H__*/
