#ifndef __RIME_HIL_COMPONENT_CONSTDEF_H__
#define __RIME_HIL_COMPONENT_CONSTDEF_H__

enum RIME_FUNCTION {
	FUNCTION_RIME_SNIFFER_ADD,
	FUNCTION_RIME_SNIFFER_REMOVE,
	FUNCTION_RIME_OUTPUT,
	FUNCTION_RIME_LAST,
};

#endif /*__RIME_HIL_COMPONENT_CONSTDEF_H__*/
