#ifndef __BUTTON_SENSOR_COMPONENT_CONSTDEF_H__
#define __BUTTON_SENSOR_COMPONENT_CONSTDEF_H__


enum BUTTON_SENSOR_FUNCTION {
	FUNCTION_BUTTON_SENSOR_GET,
	FUNCTION_BUTTON_SENSOR_LAST,
};

#define BUTTON_SENSOR_NUM_REQUIRED_OBJECTS 0
#define BUTTON_SENSOR_NUM_REQUIRED_HILOBJECTS 0

#endif /*__BUTTON_SENSOR_COMPONENT_CONSTDEF_H__*/
