#ifndef __LEDS_COMPONENT_CONSTDEF_H__
#define __LEDS_COMPONENT_CONSTDEF_H__


enum LEDS_FUNCTION {
	FUNCTION_LEDS_INIT,
	FUNCTION_LEDS_INVERT,
	FUNCTION_LEDS_ON,
	FUNCTION_LEDS_GET,
	FUNCTION_LEDS_BLINK,
	FUNCTION_LEDS_TOGGLE,
	FUNCTION_LEDS_OFF,
	FUNCTION_LEDS_LAST,
};

#define LEDS_NUM_REQUIRED_OBJECTS 0
#define LEDS_NUM_REQUIRED_HILOBJECTS 0

#endif /*__LEDS_COMPONENT_CONSTDEF_H__*/
