#ifndef __SENSORS_COMPONENT_CONSTDEF_H__
#define __SENSORS_COMPONENT_CONSTDEF_H__


enum SENSORS_FUNCTION {
	FUNCTION_SENSORS_NEXT,
	FUNCTION_SENSORS_CHANGED,
	FUNCTION_SENSORS_FIRST,
	FUNCTION_SENSORS_GET_SENSORS_EVENT,
	FUNCTION_SENSORS_FIND,
	FUNCTION_SENSORS_LAST,
};

#define SENSORS_NUM_REQUIRED_OBJECTS 0
#define SENSORS_NUM_REQUIRED_HILOBJECTS 0

#endif /*__SENSORS_COMPONENT_CONSTDEF_H__*/
