#ifndef __SERIAL_LINE_COMPONENT_CONSTDEF_H__
#define __SERIAL_LINE_COMPONENT_CONSTDEF_H__


enum SERIAL_LINE_FUNCTION {
	FUNCTION_SERIAL_LINE_INIT,
	FUNCTION_SERIAL_LINE_INPUT_BYTE,
	FUNCTION_SERIAL_LINE_LAST,
};

#define SERIAL_LINE_NUM_REQUIRED_OBJECTS 0
#define SERIAL_LINE_NUM_REQUIRED_HILOBJECTS 0

#endif /*__SERIAL_LINE_COMPONENT_CONSTDEF_H__*/
