#ifndef __ELFLOADER_COMPONENT_CONSTDEF_H__
#define __ELFLOADER_COMPONENT_CONSTDEF_H__


enum ELFLOADER_FUNCTION {
	FUNCTION_ELFLOADER_INIT,
	FUNCTION_ELFLOADER_LOAD,
	FUNCTION_ELFLOADER_LAST,
};

#define ELFLOADER_NUM_REQUIRED_OBJECTS 0
#define ELFLOADER_NUM_REQUIRED_HILOBJECTS 0

#endif /*__ELFLOADER_COMPONENT_CONSTDEF_H__*/
