#ifndef __SYMTAB_COMPONENT_CONSTDEF_H__
#define __SYMTAB_COMPONENT_CONSTDEF_H__


enum SYMTAB_FUNCTION {
	FUNCTION_SYMTAB_LOOKUP,
	FUNCTION_SYMTAB_LAST,
};

#define SYMTAB_NUM_REQUIRED_OBJECTS 0
#define SYMTAB_NUM_REQUIRED_HILOBJECTS 0

#endif /*__SYMTAB_COMPONENT_CONSTDEF_H__*/
