#ifndef __ELFLOADER_HIL_COMPONENT_CONSTDEF_H__
#define __ELFLOADER_HIL_COMPONENT_CONSTDEF_H__


enum ELFLOADER_FUNCTION {
	FUNCTION_ELFLOADER_LOAD,
	FUNCTION_ELFLOADER_INIT,
	FUNCTION_ELFLOADER_LAST,
};


enum ELFLOADER_PROCESSES {
	PROCESS_ELFLOADER_LAST,
};


#endif /*__ELFLOADER_HIL_COMPONENT_CONSTDEF_H__*/
