#ifndef __SYMTAB_HIL_COMPONENT_CONSTDEF_H__
#define __SYMTAB_HIL_COMPONENT_CONSTDEF_H__


enum SYMTAB_FUNCTION {
	FUNCTION_SYMTAB_LOOKUP,
	FUNCTION_SYMTAB_LAST,
};


enum SYMTAB_PROCESSES {
	PROCESS_SYMTAB_LAST,
};


#endif /*__SYMTAB_HIL_COMPONENT_CONSTDEF_H__*/
