#ifndef __AUTOSTART_HIL_COMPONENT_CONSTDEF_H__
#define __AUTOSTART_HIL_COMPONENT_CONSTDEF_H__


enum AUTOSTART_FUNCTION {
	FUNCTION_AUTOSTART_EXIT,
	FUNCTION_AUTOSTART_START,
	FUNCTION_AUTOSTART_LAST,
};


enum AUTOSTART_PROCESSES {
	PROCESS_AUTOSTART_LAST,
};


#endif /*__AUTOSTART_HIL_COMPONENT_CONSTDEF_H__*/
