#ifndef __MT_HIL_COMPONENT_CONSTDEF_H__
#define __MT_HIL_COMPONENT_CONSTDEF_H__


enum MT_FUNCTION {
	FUNCTION_MT_START,
	FUNCTION_MT_STOP,
	FUNCTION_MT_REMOVE,
	FUNCTION_MT_INIT,
	FUNCTION_MT_EXEC,
	FUNCTION_MT_EXIT,
	FUNCTION_MT_YIELD,
	FUNCTION_MT_LAST,
};


enum MT_PROCESSES {
	PROCESS_MT_LAST,
};


#endif /*__MT_HIL_COMPONENT_CONSTDEF_H__*/
