#ifndef __PROCESS_HIL_COMPONENT_CONSTDEF_H__
#define __PROCESS_HIL_COMPONENT_CONSTDEF_H__


enum PROCESS_FUNCTION {
	FUNCTION_PROCESS_POST_SYNCH,
	FUNCTION_PROCESS_EXIT,
	FUNCTION_PROCESS_POLL,
	FUNCTION_PROCESS_INIT,
	FUNCTION_PROCESS_NEVENTS,
	FUNCTION_PROCESS_RUN,
	FUNCTION_PROCESS_IS_RUNNING,
	FUNCTION_PROCESS_ALLOC_EVENT,
	FUNCTION_PROCESS_POST,
	FUNCTION_PROCESS_START,
	FUNCTION_PROCESS_LAST,
};


enum PROCESS_PROCESSES {
	PROCESS_PROCESS_LAST,
};


#endif /*__PROCESS_HIL_COMPONENT_CONSTDEF_H__*/
