#ifndef __CFS_COMPONENT_CONSTDEF_H__
#define __CFS_COMPONENT_CONSTDEF_H__


enum CFS_FUNCTION {
	FUNCTION_CFS_REMOVE,
	FUNCTION_CFS_OPEN,
	FUNCTION_CFS_OPENDIR,
	FUNCTION_CFS_WRITE,
	FUNCTION_CFS_CLOSE,
	FUNCTION_CFS_READDIR,
	FUNCTION_CFS_SEEK,
	FUNCTION_CFS_CLOSEDIR,
	FUNCTION_CFS_READ,
	FUNCTION_CFS_LAST,
};

#define CFS_NUM_REQUIRED_OBJECTS 0
#define CFS_NUM_REQUIRED_HILOBJECTS 0

#endif /*__CFS_COMPONENT_CONSTDEF_H__*/
