#ifndef __CFS_COFFEE_COMPONENT_CONSTDEF_H__
#define __CFS_COFFEE_COMPONENT_CONSTDEF_H__


enum CFS_COFFEE_FUNCTION {
	FUNCTION_CFS_COFFEE_CONFIGURE_LOG,
	FUNCTION_CFS_COFFEE_FORMAT,
	FUNCTION_CFS_COFFEE_GET_PROTECTED_MEM,
	FUNCTION_CFS_COFFEE_RESERVE,
	FUNCTION_CFS_COFFEE_LAST,
};

#define CFS_COFFEE_NUM_REQUIRED_OBJECTS 0
#define CFS_COFFEE_NUM_REQUIRED_HILOBJECTS 0

#endif /*__CFS_COFFEE_COMPONENT_CONSTDEF_H__*/
