#ifndef __CHAMELEON_HIL_COMPONENT_CONSTDEF_H__
#define __CHAMELEON_HIL_COMPONENT_CONSTDEF_H__

enum CHAMELEON_FUNCTION {
	FUNCTION_CHAMELEON_PARSE,
	FUNCTION_CHAMELEON_INIT,
	FUNCTION_CHAMELEON_CREATE,
	FUNCTION_CHAMELEON_HDRSIZE,
	FUNCTION_CHAMELEON_LAST,
};

#endif /*__CHAMELEON_HIL_COMPONENT_CONSTDEF_H__*/
