#ifndef __NEIGHBOR_DISCOVERY_COMPONENT_CONSTDEF_H__
#define __NEIGHBOR_DISCOVERY_COMPONENT_CONSTDEF_H__


enum NEIGHBOR_DISCOVERY_FUNCTION {
	FUNCTION_NEIGHBOR_DISCOVERY_START,
	FUNCTION_NEIGHBOR_DISCOVERY_CLOSE,
	FUNCTION_NEIGHBOR_DISCOVERY_SET_VAL,
	FUNCTION_NEIGHBOR_DISCOVERY_OPEN,
	FUNCTION_NEIGHBOR_DISCOVERY_LAST,
};


enum NEIGHBOR_DISCOVERY_PROCESSES {
	PROCESS_NEIGHBOR_DISCOVERY_LAST,
};


#endif /*__NEIGHBOR_DISCOVERY_COMPONENT_CONSTDEF_H__*/
