#ifndef __POLITE_ANNOUNCEMENT_COMPONENT_CONSTDEF_H__
#define __POLITE_ANNOUNCEMENT_COMPONENT_CONSTDEF_H__


enum POLITE_ANNOUNCEMENT_FUNCTION {
	FUNCTION_POLITE_ANNOUNCEMENT_INIT,
	FUNCTION_POLITE_ANNOUNCEMENT_LAST,
};

#endif /*__POLITE_ANNOUNCEMENT_COMPONENT_CONSTDEF_H__*/
