#ifndef __ROUTE_DISCOVERY_COMPONENT_CONSTDEF_H__
#define __ROUTE_DISCOVERY_COMPONENT_CONSTDEF_H__


enum ROUTE_DISCOVERY_FUNCTION {
	FUNCTION_ROUTE_DISCOVERY_DISCOVER,
	FUNCTION_ROUTE_DISCOVERY_CLOSE,
	FUNCTION_ROUTE_DISCOVERY_OPEN,
	FUNCTION_ROUTE_DISCOVERY_LAST,
};


enum ROUTE_DISCOVERY_PROCESSES {
	PROCESS_ROUTE_DISCOVERY_LAST,
};


#endif /*__ROUTE_DISCOVERY_COMPONENT_CONSTDEF_H__*/
