#ifndef __RUCB_COMPONENT_CONSTDEF_H__
#define __RUCB_COMPONENT_CONSTDEF_H__


enum RUCB_FUNCTION {
	FUNCTION_RUCB_SEND,
	FUNCTION_RUCB_OPEN,
	FUNCTION_RUCB_CLOSE,
	FUNCTION_RUCB_LAST,
};

#endif /*__RUCB_COMPONENT_CONSTDEF_H__*/
