#ifndef __RUDOLPH1_COMPONENT_CONSTDEF_H__
#define __RUDOLPH1_COMPONENT_CONSTDEF_H__


enum RUDOLPH1_FUNCTION {
	FUNCTION_RUDOLPH1_CLOSE,
	FUNCTION_RUDOLPH1_OPEN,
	FUNCTION_RUDOLPH1_STOP,
	FUNCTION_RUDOLPH1_SEND,
	FUNCTION_RUDOLPH1_LAST,
};

#endif /*__RUDOLPH1_COMPONENT_CONSTDEF_H__*/
