#ifndef __RUDOLPH2_COMPONENT_CONSTDEF_H__
#define __RUDOLPH2_COMPONENT_CONSTDEF_H__


enum RUDOLPH2_FUNCTION {
	FUNCTION_RUDOLPH2_CLOSE,
	FUNCTION_RUDOLPH2_OPEN,
	FUNCTION_RUDOLPH2_STOP,
	FUNCTION_RUDOLPH2_SEND,
	FUNCTION_RUDOLPH2_LAST,
};


enum RUDOLPH2_PROCESSES {
	PROCESS_RUDOLPH2_LAST,
};


#endif /*__RUDOLPH2_COMPONENT_CONSTDEF_H__*/
