#ifndef __UNICAST_COMPONENT_CONSTDEF_H__
#define __UNICAST_COMPONENT_CONSTDEF_H__


enum UNICAST_FUNCTION {
	FUNCTION_UNICAST_SEND,
	FUNCTION_UNICAST_CLOSE,
	FUNCTION_UNICAST_OPEN,
	FUNCTION_UNICAST_LAST,
};


enum UNICAST_PROCESSES {
	PROCESS_UNICAST_LAST,
};


#endif /*__UNICAST_COMPONENT_CONSTDEF_H__*/
