#ifndef __CTIMER_HIL_COMPONENT_CONSTDEF_H__
#define __CTIMER_HIL_COMPONENT_CONSTDEF_H__

enum CTIMER_FUNCTION {
	FUNCTION_CTIMER_RESET,
	FUNCTION_CTIMER_SET,
	FUNCTION_CTIMER_RESTART,
	FUNCTION_CTIMER_STOP,
	FUNCTION_CTIMER_INIT,
	FUNCTION_CTIMER_EXPIRED,
	FUNCTION_CTIMER_LAST,
};

#endif /*__CTIMER_HIL_COMPONENT_CONSTDEF_H__*/
