#ifndef __RTIMER_HIL_COMPONENT_CONSTDEF_H__
#define __RTIMER_HIL_COMPONENT_CONSTDEF_H__

enum RTIMER_FUNCTION {
	FUNCTION_RTIMER_SET,
	FUNCTION_RTIMER_NOW,
	FUNCTION_RTIMER_INIT,
	FUNCTION_RTIMER_RUN_NEXT,
	FUNCTION_RTIMER_LAST,
};

#endif /*__RTIMER_HIL_COMPONENT_CONSTDEF_H__*/
