#ifndef __STIMER_HIL_COMPONENT_CONSTDEF_H__
#define __STIMER_HIL_COMPONENT_CONSTDEF_H__

enum STIMER_FUNCTION {
	FUNCTION_STIMER_RESTART,
	FUNCTION_STIMER_EXPIRED,
	FUNCTION_STIMER_RESET,
	FUNCTION_STIMER_REMAINING,
	FUNCTION_STIMER_SET,
	FUNCTION_STIMER_ELAPSED,
	FUNCTION_STIMER_LAST,
};

#endif /*__STIMER_HIL_COMPONENT_CONSTDEF_H__*/
