#ifndef __TIMER_HIL_COMPONENT_CONSTDEF_H__
#define __TIMER_HIL_COMPONENT_CONSTDEF_H__


enum TIMER_FUNCTION {
	FUNCTION_TIMER_REMAINING,
	FUNCTION_TIMER_RESTART,
	FUNCTION_TIMER_SET,
	FUNCTION_TIMER_EXPIRED,
	FUNCTION_TIMER_RESET,
	FUNCTION_TIMER_LAST,
};


enum TIMER_PROCESSES {
	PROCESS_TIMER_LAST,
};


#endif /*__TIMER_HIL_COMPONENT_CONSTDEF_H__*/
