#ifndef __EXAMPLE_RUNICAST_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_RUNICAST_COMPONENT_CONSTDEF_H__


enum EXAMPLE_RUNICAST_FUNCTION {
	FUNCTION_EXAMPLE_RUNICAST_LAST,
};

#define EXAMPLE_RUNICAST_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_RUNICAST_NUM_REQUIRED_HILOBJECTS 5

#endif /*__EXAMPLE_RUNICAST_COMPONENT_CONSTDEF_H__*/
