#ifndef __EXAMPLE_MULTIHOP_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_MULTIHOP_COMPONENT_CONSTDEF_H__


enum EXAMPLE_MULTIHOP_FUNCTION {
	FUNCTION_EXAMPLE_MULTIHOP_LAST,
};

#define EXAMPLE_MULTIHOP_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_MULTIHOP_NUM_REQUIRED_HILOBJECTS 9

#endif /*__EXAMPLE_MULTIHOP_COMPONENT_CONSTDEF_H__*/
