#ifndef __EXAMPLE_TRICKLE_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_TRICKLE_COMPONENT_CONSTDEF_H__


enum EXAMPLE_TRICKLE_FUNCTION {
	FUNCTION_EXAMPLE_TRICKLE_LAST,
};

#define EXAMPLE_TRICKLE_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_TRICKLE_NUM_REQUIRED_HILOBJECTS 3

#endif /*__EXAMPLE_TRICKLE_COMPONENT_CONSTDEF_H__*/
