#ifndef __EXAMPLE_ABC_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_ABC_COMPONENT_CONSTDEF_H__


enum EXAMPLE_ABC_FUNCTION {
	FUNCTION_EXAMPLE_ABC_LAST,
};

#define EXAMPLE_ABC_NUM_REQUIRED_OBJECTS 0
#define EXAMPLE_ABC_NUM_REQUIRED_HILOBJECTS 4

#endif /*__EXAMPLE_ABC_COMPONENT_CONSTDEF_H__*/
