#ifndef __EXAMPLE_POLITE_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_POLITE_COMPONENT_CONSTDEF_H__


enum EXAMPLE_POLITE_FUNCTION {
	FUNCTION_EXAMPLE_POLITE_LAST,
};

#define EXAMPLE_POLITE_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_POLITE_NUM_REQUIRED_HILOBJECTS 2

#endif /*__EXAMPLE_POLITE_COMPONENT_CONSTDEF_H__*/
