#ifndef __EXAMPLE_COLLECT_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_COLLECT_COMPONENT_CONSTDEF_H__


enum EXAMPLE_COLLECT_FUNCTION {
	FUNCTION_EXAMPLE_COLLECT_LAST,
};

#define EXAMPLE_COLLECT_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_COLLECT_NUM_REQUIRED_HILOBJECTS 5

#endif /*__EXAMPLE_COLLECT_COMPONENT_CONSTDEF_H__*/
