#ifndef __EXAMPLE_RUCB_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_RUCB_COMPONENT_CONSTDEF_H__


enum EXAMPLE_RUCB_FUNCTION {
	FUNCTION_EXAMPLE_RUCB_LAST,
};

#define EXAMPLE_RUCB_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_RUCB_NUM_REQUIRED_HILOBJECTS 5

#endif /*__EXAMPLE_RUCB_COMPONENT_CONSTDEF_H__*/
