#ifndef __EXAMPLE_NEIGHBORS_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_NEIGHBORS_COMPONENT_CONSTDEF_H__


enum EXAMPLE_NEIGHBORS_FUNCTION {
	FUNCTION_EXAMPLE_NEIGHBORS_LAST,
};

#define EXAMPLE_NEIGHBORS_NUM_REQUIRED_OBJECTS 2
#define EXAMPLE_NEIGHBORS_NUM_REQUIRED_HILOBJECTS 6

#endif /*__EXAMPLE_NEIGHBORS_COMPONENT_CONSTDEF_H__*/
