#ifndef __EXAMPLE_UNICAST_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_UNICAST_COMPONENT_CONSTDEF_H__


enum EXAMPLE_UNICAST_FUNCTION {
	FUNCTION_EXAMPLE_UNICAST_LAST,
};

#define EXAMPLE_UNICAST_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_UNICAST_NUM_REQUIRED_HILOBJECTS 3

#endif /*__EXAMPLE_UNICAST_COMPONENT_CONSTDEF_H__*/
