#ifndef __EXAMPLE_RUDOLPH0_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_RUDOLPH0_COMPONENT_CONSTDEF_H__


enum EXAMPLE_RUDOLPH0_FUNCTION {
	FUNCTION_EXAMPLE_RUDOLPH0_LAST,
};

#define EXAMPLE_RUDOLPH0_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_RUDOLPH0_NUM_REQUIRED_HILOBJECTS 5

#endif /*__EXAMPLE_RUDOLPH0_COMPONENT_CONSTDEF_H__*/
