#ifndef __EXAMPLE_BROADCAST_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_BROADCAST_COMPONENT_CONSTDEF_H__


enum EXAMPLE_BROADCAST_FUNCTION {
	FUNCTION_EXAMPLE_BROADCAST_LAST,
};

#define EXAMPLE_BROADCAST_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_BROADCAST_NUM_REQUIRED_HILOBJECTS 3

#endif /*__EXAMPLE_BROADCAST_COMPONENT_CONSTDEF_H__*/
