#ifndef __EXAMPLE_MESH_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_MESH_COMPONENT_CONSTDEF_H__


enum EXAMPLE_MESH_FUNCTION {
	FUNCTION_EXAMPLE_MESH_LAST,
};

#define EXAMPLE_MESH_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_MESH_NUM_REQUIRED_HILOBJECTS 3

#endif /*__EXAMPLE_MESH_COMPONENT_CONSTDEF_H__*/
