#ifndef __EXAMPLE_RUDOLPH2_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_RUDOLPH2_COMPONENT_CONSTDEF_H__


enum EXAMPLE_RUDOLPH2_FUNCTION {
	FUNCTION_EXAMPLE_RUDOLPH2_LAST,
};

#define EXAMPLE_RUDOLPH2_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_RUDOLPH2_NUM_REQUIRED_HILOBJECTS 6

#endif /*__EXAMPLE_RUDOLPH2_COMPONENT_CONSTDEF_H__*/
