#ifndef __EXAMPLE_RUDOLPH1_COMPONENT_CONSTDEF_H__
#define __EXAMPLE_RUDOLPH1_COMPONENT_CONSTDEF_H__


enum EXAMPLE_RUDOLPH1_FUNCTION {
	FUNCTION_EXAMPLE_RUDOLPH1_LAST,
};

#define EXAMPLE_RUDOLPH1_NUM_REQUIRED_OBJECTS 1
#define EXAMPLE_RUDOLPH1_NUM_REQUIRED_HILOBJECTS 7

#endif /*__EXAMPLE_RUDOLPH1_COMPONENT_CONSTDEF_H__*/
