
CORE_RUNTIME = kernel.c component-db.c #kernel-list.c component-factory.c
CORE_DEPLOYTIME = #serial-pkg-source.c pkg-manager.c pkg-installer.c pkg-manager.c pkg-repository.c
KERNEL_CORE = $(CORE_RUNTIME) $(CORE_DEPLOYTIME)
KERNELFILES = $(KERNEL_CORE)

KERNEL_BASEDIR = $(GITAR)/src/kernel/
KERNELDIRS = ${addprefix $(KERNEL_BASEDIR), core  system-facade core/deploytime-mgmt core/runtime-mgmt . }

#${info including kernel source files '$(KERNELFILES)' in dirs '$(KERNELDIRS)'}
