#ifndef __BUTTON_SENSOR_HIL_COMPONENT_CONSTDEF_H__
#define __BUTTON_SENSOR_HIL_COMPONENT_CONSTDEF_H__

enum BUTTON_SENSOR_FUNCTION {
	FUNCTION_BUTTON_SENSOR_LAST,
};

#endif /*__BUTTON_SENSOR_HIL_COMPONENT_CONSTDEF_H__*/
