#ifndef __BUTTON_SENSOR_CONSTDEF_H__
#define __BUTTON_SENSOR_CONSTDEF_H__

enum BUTTON_SENSOR_FUNCTION {
	FUNCTION_BUTTON_SENSOR_GET,
	FUNCTION_BUTTON_SENSOR_LAST,
};


enum BUTTON_SENSOR_PROCESSES {
	PROCESS_BUTTON_SENSOR_LAST,
};

#endif
