#ifndef __SENSORS_HIL_COMPONENT_CONSTDEF_H__
#define __SENSORS_HIL_COMPONENT_CONSTDEF_H__

enum SENSORS_FUNCTION {
	FUNCTION_SENSORS_NEXT,
	FUNCTION_SENSORS_CHANGED,
	FUNCTION_SENSORS_FIND,
	FUNCTION_SENSORS_FIRST,
	FUNCTION_SENSORS_LAST,
};

#endif /*__SENSORS_HIL_COMPONENT_CONSTDEF_H__*/
