#ifndef __SERIAL_LINE_HIL_COMPONENT_CONSTDEF_H__
#define __SERIAL_LINE_HIL_COMPONENT_CONSTDEF_H__

enum SERIAL_LINE_FUNCTION {
	FUNCTION_SERIAL_LINE_INIT,
	FUNCTION_SERIAL_LINE_INPUT_BYTE,
	FUNCTION_SERIAL_LINE_LAST,
};

#endif /*__SERIAL_LINE_HIL_COMPONENT_CONSTDEF_H__*/
