#ifndef __SPI_HIL_COMPONENT_CONSTDEF_H__
#define __SPI_HIL_COMPONENT_CONSTDEF_H__


enum SPI_FUNCTION {
	FUNCTION_SPI_INIT,
	FUNCTION_SPI_LAST,
};


enum SPI_PROCESSES {
	PROCESS_SPI_LAST,
};


#endif /*__SPI_HIL_COMPONENT_CONSTDEF_H__*/
