#ifndef __WATCHDOG_HIL_COMPONENT_CONSTDEF_H__
#define __WATCHDOG_HIL_COMPONENT_CONSTDEF_H__

enum WATCHDOG_FUNCTION {
	FUNCTION_WATCHDOG_REBOOT,
	FUNCTION_WATCHDOG_STOP,
	FUNCTION_WATCHDOG_START,
	FUNCTION_WATCHDOG_PERIODIC,
	FUNCTION_WATCHDOG_INIT,
	FUNCTION_WATCHDOG_LAST,
};

#endif /*__WATCHDOG_HIL_COMPONENT_CONSTDEF_H__*/
