#ifndef __XMEM_HIL_COMPONENT_CONSTDEF_H__
#define __XMEM_HIL_COMPONENT_CONSTDEF_H__


enum XMEM_FUNCTION {
	FUNCTION_XMEM_PREAD,
	FUNCTION_XMEM_INIT,
	FUNCTION_XMEM_ERASE,
	FUNCTION_XMEM_PWRITE,
	FUNCTION_XMEM_LAST,
};


enum XMEM_PROCESSES {
	PROCESS_XMEM_LAST,
};


#endif /*__XMEM_HIL_COMPONENT_CONSTDEF_H__*/
