#ifndef __AUTOSTART_COMPONENT_CONSTDEF_H__
#define __AUTOSTART_COMPONENT_CONSTDEF_H__


enum AUTOSTART_FUNCTION {
	FUNCTION_AUTOSTART_EXIT,
	FUNCTION_AUTOSTART_START,
	FUNCTION_AUTOSTART_LAST,
};

#define AUTOSTART_NUM_REQUIRED_OBJECTS 0
#define AUTOSTART_NUM_REQUIRED_HILOBJECTS 0

#endif /*__AUTOSTART_COMPONENT_CONSTDEF_H__*/
