#ifndef __MT_COMPONENT_CONSTDEF_H__
#define __MT_COMPONENT_CONSTDEF_H__


enum MT_FUNCTION {
	FUNCTION_MT_EXIT,
	FUNCTION_MT_REMOVE,
	FUNCTION_MT_INIT,
	FUNCTION_MT_YIELD,
	FUNCTION_MT_EXEC,
	FUNCTION_MT_STOP,
	FUNCTION_MT_START,
	FUNCTION_MT_LAST,
};

#define MT_NUM_REQUIRED_OBJECTS 0
#define MT_NUM_REQUIRED_HILOBJECTS 0

#endif /*__MT_COMPONENT_CONSTDEF_H__*/
