#ifndef __PROCESS_COMPONENT_CONSTDEF_H__
#define __PROCESS_COMPONENT_CONSTDEF_H__


enum PROCESS_FUNCTION {
	FUNCTION_PROCESS_IS_RUNNING,
	FUNCTION_PROCESS_NEVENTS,
	FUNCTION_PROCESS_POLL,
	FUNCTION_PROCESS_POST,
	FUNCTION_PROCESS_START,
	FUNCTION_PROCESS_POST_SYNCH,
	FUNCTION_PROCESS_EXIT,
	FUNCTION_PROCESS_GET_CURRENT_PROCESS,
	FUNCTION_PROCESS_ALLOC_EVENT,
	FUNCTION_PROCESS_INIT,
	FUNCTION_PROCESS_RUN,
	FUNCTION_PROCESS_LAST,
};

#define PROCESS_NUM_REQUIRED_OBJECTS 0
#define PROCESS_NUM_REQUIRED_HILOBJECTS 0

#endif /*__PROCESS_COMPONENT_CONSTDEF_H__*/
