#ifndef __BROADCAST_COMPONENT_CONSTDEF_H__
#define __BROADCAST_COMPONENT_CONSTDEF_H__


enum BROADCAST_FUNCTION {
	FUNCTION_BROADCAST_SEND,
	FUNCTION_BROADCAST_OPEN,
	FUNCTION_BROADCAST_CLOSE,
	FUNCTION_BROADCAST_LAST,
};

#endif /*__BROADCAST_COMPONENT_CONSTDEF_H__*/
