#ifndef __COLLECT_COMPONENT_CONSTDEF_H__
#define __COLLECT_COMPONENT_CONSTDEF_H__


enum COLLECT_FUNCTION {
	FUNCTION_COLLECT_SET_KEEPALIVE,
	FUNCTION_COLLECT_CLOSE,
	FUNCTION_COLLECT_OPEN,
	FUNCTION_COLLECT_PRINT_STATS,
	FUNCTION_COLLECT_DEPTH,
	FUNCTION_COLLECT_SET_SINK,
	FUNCTION_COLLECT_PARENT,
	FUNCTION_COLLECT_SEND,
	FUNCTION_COLLECT_LAST,
};

#endif /*__COLLECT_COMPONENT_CONSTDEF_H__*/
