#ifndef __IPOLITE_COMPONENT_CONSTDEF_H__
#define __IPOLITE_COMPONENT_CONSTDEF_H__


enum IPOLITE_FUNCTION {
	FUNCTION_IPOLITE_SEND,
	FUNCTION_IPOLITE_OPEN,
	FUNCTION_IPOLITE_CLOSE,
	FUNCTION_IPOLITE_CANCEL,
	FUNCTION_IPOLITE_LAST,
};

#define IPOLITE_NUM_REQUIRED_OBJECTS 1
#define IPOLITE_NUM_REQUIRED_HILOBJECTS 5

#endif /*__IPOLITE_COMPONENT_CONSTDEF_H__*/
