#ifndef __NETFLOOD_COMPONENT_CONSTDEF_H__
#define __NETFLOOD_COMPONENT_CONSTDEF_H__


enum NETFLOOD_FUNCTION {
	FUNCTION_NETFLOOD_OPEN,
	FUNCTION_NETFLOOD_SEND,
	FUNCTION_NETFLOOD_CLOSE,
	FUNCTION_NETFLOOD_LAST,
};

#define NETFLOOD_NUM_REQUIRED_OBJECTS 1
#define NETFLOOD_NUM_REQUIRED_HILOBJECTS 4

#endif /*__NETFLOOD_COMPONENT_CONSTDEF_H__*/
