#ifndef __NETFLOOD_COMPONENT_CONSTDEF_H__
#define __NETFLOOD_COMPONENT_CONSTDEF_H__


enum NETFLOOD_FUNCTION {
	FUNCTION_NETFLOOD_OPEN,
	FUNCTION_NETFLOOD_CLOSE,
	FUNCTION_NETFLOOD_SEND,
	FUNCTION_NETFLOOD_LAST,
};

#endif /*__NETFLOOD_COMPONENT_CONSTDEF_H__*/
