#ifndef __POLITE_COMPONENT_CONSTDEF_H__
#define __POLITE_COMPONENT_CONSTDEF_H__


enum POLITE_FUNCTION {
	FUNCTION_POLITE_SEND,
	FUNCTION_POLITE_OPEN,
	FUNCTION_POLITE_CLOSE,
	FUNCTION_POLITE_CANCEL,
	FUNCTION_POLITE_LAST,
};

#define POLITE_NUM_REQUIRED_OBJECTS 0
#define POLITE_NUM_REQUIRED_HILOBJECTS 6

#endif /*__POLITE_COMPONENT_CONSTDEF_H__*/
