#ifndef __RMH_COMPONENT_CONSTDEF_H__
#define __RMH_COMPONENT_CONSTDEF_H__


enum RMH_FUNCTION {
	FUNCTION_RMH_CLOSE,
	FUNCTION_RMH_SEND,
	FUNCTION_RMH_OPEN,
	FUNCTION_RMH_LAST,
};

#define RMH_NUM_REQUIRED_OBJECTS 1
#define RMH_NUM_REQUIRED_HILOBJECTS 2

#endif /*__RMH_COMPONENT_CONSTDEF_H__*/
