#ifndef __ROUTE_COMPONENT_CONSTDEF_H__
#define __ROUTE_COMPONENT_CONSTDEF_H__


enum ROUTE_FUNCTION {
	FUNCTION_ROUTE_NUM,
	FUNCTION_ROUTE_REMOVE,
	FUNCTION_ROUTE_GET,
	FUNCTION_ROUTE_FLUSH_ALL,
	FUNCTION_ROUTE_SET_LIFETIME,
	FUNCTION_ROUTE_INIT,
	FUNCTION_ROUTE_REFRESH,
	FUNCTION_ROUTE_DECAY,
	FUNCTION_ROUTE_ADD,
	FUNCTION_ROUTE_LOOKUP,
	FUNCTION_ROUTE_LAST,
};

#define ROUTE_NUM_REQUIRED_OBJECTS 0
#define ROUTE_NUM_REQUIRED_HILOBJECTS 4

#endif /*__ROUTE_COMPONENT_CONSTDEF_H__*/
