#ifndef __RUCB_COMPONENT_CONSTDEF_H__
#define __RUCB_COMPONENT_CONSTDEF_H__


enum RUCB_FUNCTION {
	FUNCTION_RUCB_CLOSE,
	FUNCTION_RUCB_OPEN,
	FUNCTION_RUCB_SEND,
	FUNCTION_RUCB_LAST,
};

#define RUCB_NUM_REQUIRED_OBJECTS 1
#define RUCB_NUM_REQUIRED_HILOBJECTS 2

#endif /*__RUCB_COMPONENT_CONSTDEF_H__*/
