#ifndef __RUDOLPH2_COMPONENT_CONSTDEF_H__
#define __RUDOLPH2_COMPONENT_CONSTDEF_H__


enum RUDOLPH2_FUNCTION {
	FUNCTION_RUDOLPH2_STOP,
	FUNCTION_RUDOLPH2_SEND,
	FUNCTION_RUDOLPH2_CLOSE,
	FUNCTION_RUDOLPH2_OPEN,
	FUNCTION_RUDOLPH2_LAST,
};

#define RUDOLPH2_NUM_REQUIRED_OBJECTS 1
#define RUDOLPH2_NUM_REQUIRED_HILOBJECTS 2

#endif /*__RUDOLPH2_COMPONENT_CONSTDEF_H__*/
