#ifndef __RUDOLPH0_COMPONENT_CONSTDEF_H__
#define __RUDOLPH0_COMPONENT_CONSTDEF_H__


enum RUDOLPH0_FUNCTION {
	FUNCTION_RUDOLPH0_CLOSE,
	FUNCTION_RUDOLPH0_VERSION,
	FUNCTION_RUDOLPH0_SEND,
	FUNCTION_RUDOLPH0_OPEN,
	FUNCTION_RUDOLPH0_SET_VERSION,
	FUNCTION_RUDOLPH0_FORCE_RESTART,
	FUNCTION_RUDOLPH0_STOP,
	FUNCTION_RUDOLPH0_LAST,
};

#define RUDOLPH0_NUM_REQUIRED_OBJECTS 2
#define RUDOLPH0_NUM_REQUIRED_HILOBJECTS 1

#endif /*__RUDOLPH0_COMPONENT_CONSTDEF_H__*/
