#ifndef __RUNICAST_COMPONENT_CONSTDEF_H__
#define __RUNICAST_COMPONENT_CONSTDEF_H__


enum RUNICAST_FUNCTION {
	FUNCTION_RUNICAST_OPEN,
	FUNCTION_RUNICAST_SEND,
	FUNCTION_RUNICAST_CLOSE,
	FUNCTION_RUNICAST_IS_TRANSMITTING,
	FUNCTION_RUNICAST_LAST,
};

#define RUNICAST_NUM_REQUIRED_OBJECTS 1
#define RUNICAST_NUM_REQUIRED_HILOBJECTS 3

#endif /*__RUNICAST_COMPONENT_CONSTDEF_H__*/
