#ifndef __TRICKLE_COMPONENT_CONSTDEF_H__
#define __TRICKLE_COMPONENT_CONSTDEF_H__


enum TRICKLE_FUNCTION {
	FUNCTION_TRICKLE_SEND,
	FUNCTION_TRICKLE_OPEN,
	FUNCTION_TRICKLE_CLOSE,
	FUNCTION_TRICKLE_LAST,
};

#define TRICKLE_NUM_REQUIRED_OBJECTS 1
#define TRICKLE_NUM_REQUIRED_HILOBJECTS 5

#endif /*__TRICKLE_COMPONENT_CONSTDEF_H__*/
