#ifndef __UNICAST_COMPONENT_CONSTDEF_H__
#define __UNICAST_COMPONENT_CONSTDEF_H__


enum UNICAST_FUNCTION {
	FUNCTION_UNICAST_CLOSE,
	FUNCTION_UNICAST_SEND,
	FUNCTION_UNICAST_OPEN,
	FUNCTION_UNICAST_LAST,
};

#define UNICAST_NUM_REQUIRED_OBJECTS 1
#define UNICAST_NUM_REQUIRED_HILOBJECTS 3

#endif /*__UNICAST_COMPONENT_CONSTDEF_H__*/
